// This file was generated by Mendix Modeler 7.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pubsub.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the PubSub module
	public static void iVK_ListenToSubscription(IContext context, pubsub.proxies.Topic _topic, pubsub.proxies.Subscription _subscription)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Topic", _topic == null ? null : _topic.getMendixObject());
			params.put("Subscription", _subscription == null ? null : _subscription.getMendixObject());
			Core.execute(context, "PubSub.IVK_ListenToSubscription", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_PublishMessage(IContext context, pubsub.proxies.PublishHelper _publishHelper)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("PublishHelper", _publishHelper == null ? null : _publishHelper.getMendixObject());
			Core.execute(context, "PubSub.IVK_PublishMessage", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_ShowNewPublish(IContext context, main.proxies.Project _project, pubsub.proxies.Topic _topic)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Project", _project == null ? null : _project.getMendixObject());
			params.put("Topic", _topic == null ? null : _topic.getMendixObject());
			Core.execute(context, "PubSub.IVK_ShowNewPublish", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_ShowNewSubscription(IContext context, pubsub.proxies.Topic _topic)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Topic", _topic == null ? null : _topic.getMendixObject());
			Core.execute(context, "PubSub.IVK_ShowNewSubscription", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_ShowNewTopic(IContext context, main.proxies.Project _project)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Project", _project == null ? null : _project.getMendixObject());
			Core.execute(context, "PubSub.IVK_ShowNewTopic", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_StopListeningToSubscription(IContext context, pubsub.proxies.Subscription _subscription, pubsub.proxies.Topic _topic)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Subscription", _subscription == null ? null : _subscription.getMendixObject());
			params.put("Topic", _topic == null ? null : _topic.getMendixObject());
			Core.execute(context, "PubSub.IVK_StopListeningToSubscription", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void onFailure(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "PubSub.OnFailure", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void onMessage(IContext context, java.lang.String _attributes, java.lang.String _payload)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Attributes", _attributes);
			params.put("Payload", _payload);
			Core.execute(context, "PubSub.OnMessage", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}