// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pubsub.proxies;

public class PublishHelper
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject publishHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PubSub.PublishHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Payload("Payload"),
		PublishHelper_Topic("PubSub.PublishHelper_Topic");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PublishHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "PubSub.PublishHelper"));
	}

	protected PublishHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject publishHelperMendixObject)
	{
		if (publishHelperMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("PubSub.PublishHelper", publishHelperMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a PubSub.PublishHelper");

		this.publishHelperMendixObject = publishHelperMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'PublishHelper.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static pubsub.proxies.PublishHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return pubsub.proxies.PublishHelper.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static pubsub.proxies.PublishHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new pubsub.proxies.PublishHelper(context, mendixObject);
	}

	public static pubsub.proxies.PublishHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return pubsub.proxies.PublishHelper.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Payload
	 */
	public final java.lang.String getPayload()
	{
		return getPayload(getContext());
	}

	/**
	 * @param context
	 * @return value of Payload
	 */
	public final java.lang.String getPayload(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Payload.toString());
	}

	/**
	 * Set value of Payload
	 * @param payload
	 */
	public final void setPayload(java.lang.String payload)
	{
		setPayload(getContext(), payload);
	}

	/**
	 * Set value of Payload
	 * @param context
	 * @param payload
	 */
	public final void setPayload(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String payload)
	{
		getMendixObject().setValue(context, MemberNames.Payload.toString(), payload);
	}

	/**
	 * @return value of PublishHelper_Topic
	 */
	public final pubsub.proxies.Topic getPublishHelper_Topic() throws com.mendix.core.CoreException
	{
		return getPublishHelper_Topic(getContext());
	}

	/**
	 * @param context
	 * @return value of PublishHelper_Topic
	 */
	public final pubsub.proxies.Topic getPublishHelper_Topic(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		pubsub.proxies.Topic result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PublishHelper_Topic.toString());
		if (identifier != null)
			result = pubsub.proxies.Topic.load(context, identifier);
		return result;
	}

	/**
	 * Set value of PublishHelper_Topic
	 * @param publishhelper_topic
	 */
	public final void setPublishHelper_Topic(pubsub.proxies.Topic publishhelper_topic)
	{
		setPublishHelper_Topic(getContext(), publishhelper_topic);
	}

	/**
	 * Set value of PublishHelper_Topic
	 * @param context
	 * @param publishhelper_topic
	 */
	public final void setPublishHelper_Topic(com.mendix.systemwideinterfaces.core.IContext context, pubsub.proxies.Topic publishhelper_topic)
	{
		if (publishhelper_topic == null)
			getMendixObject().setValue(context, MemberNames.PublishHelper_Topic.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.PublishHelper_Topic.toString(), publishhelper_topic.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return publishHelperMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final pubsub.proxies.PublishHelper that = (pubsub.proxies.PublishHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "PubSub.PublishHelper";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
