// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pubsub.proxies;

public class Subscription
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject subscriptionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PubSub.Subscription";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_name("_name"),
		Subscription_Topic("PubSub.Subscription_Topic");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Subscription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "PubSub.Subscription"));
	}

	protected Subscription(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject subscriptionMendixObject)
	{
		if (subscriptionMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("PubSub.Subscription", subscriptionMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a PubSub.Subscription");

		this.subscriptionMendixObject = subscriptionMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Subscription.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static pubsub.proxies.Subscription initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return pubsub.proxies.Subscription.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static pubsub.proxies.Subscription initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new pubsub.proxies.Subscription(context, mendixObject);
	}

	public static pubsub.proxies.Subscription load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return pubsub.proxies.Subscription.initialize(context, mendixObject);
	}

	public static java.util.List<pubsub.proxies.Subscription> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<pubsub.proxies.Subscription> result = new java.util.ArrayList<pubsub.proxies.Subscription>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//PubSub.Subscription" + xpathConstraint))
			result.add(pubsub.proxies.Subscription.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _name
	 */
	public final java.lang.String get_name()
	{
		return get_name(getContext());
	}

	/**
	 * @param context
	 * @return value of _name
	 */
	public final java.lang.String get_name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._name.toString());
	}

	/**
	 * Set value of _name
	 * @param _name
	 */
	public final void set_name(java.lang.String _name)
	{
		set_name(getContext(), _name);
	}

	/**
	 * Set value of _name
	 * @param context
	 * @param _name
	 */
	public final void set_name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _name)
	{
		getMendixObject().setValue(context, MemberNames._name.toString(), _name);
	}

	/**
	 * @return value of Subscription_Topic
	 */
	public final pubsub.proxies.Topic getSubscription_Topic() throws com.mendix.core.CoreException
	{
		return getSubscription_Topic(getContext());
	}

	/**
	 * @param context
	 * @return value of Subscription_Topic
	 */
	public final pubsub.proxies.Topic getSubscription_Topic(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		pubsub.proxies.Topic result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Subscription_Topic.toString());
		if (identifier != null)
			result = pubsub.proxies.Topic.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Subscription_Topic
	 * @param subscription_topic
	 */
	public final void setSubscription_Topic(pubsub.proxies.Topic subscription_topic)
	{
		setSubscription_Topic(getContext(), subscription_topic);
	}

	/**
	 * Set value of Subscription_Topic
	 * @param context
	 * @param subscription_topic
	 */
	public final void setSubscription_Topic(com.mendix.systemwideinterfaces.core.IContext context, pubsub.proxies.Topic subscription_topic)
	{
		if (subscription_topic == null)
			getMendixObject().setValue(context, MemberNames.Subscription_Topic.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Subscription_Topic.toString(), subscription_topic.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return subscriptionMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final pubsub.proxies.Subscription that = (pubsub.proxies.Subscription) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "PubSub.Subscription";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
