// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pubsub.proxies;

public class Topic
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject topicMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PubSub.Topic";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_name("_name"),
		Topic_Project("PubSub.Topic_Project");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Topic(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "PubSub.Topic"));
	}

	protected Topic(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject topicMendixObject)
	{
		if (topicMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("PubSub.Topic", topicMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a PubSub.Topic");

		this.topicMendixObject = topicMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Topic.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static pubsub.proxies.Topic initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return pubsub.proxies.Topic.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static pubsub.proxies.Topic initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new pubsub.proxies.Topic(context, mendixObject);
	}

	public static pubsub.proxies.Topic load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return pubsub.proxies.Topic.initialize(context, mendixObject);
	}

	public static java.util.List<pubsub.proxies.Topic> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<pubsub.proxies.Topic> result = new java.util.ArrayList<pubsub.proxies.Topic>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//PubSub.Topic" + xpathConstraint))
			result.add(pubsub.proxies.Topic.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _name
	 */
	public final java.lang.String get_name()
	{
		return get_name(getContext());
	}

	/**
	 * @param context
	 * @return value of _name
	 */
	public final java.lang.String get_name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._name.toString());
	}

	/**
	 * Set value of _name
	 * @param _name
	 */
	public final void set_name(java.lang.String _name)
	{
		set_name(getContext(), _name);
	}

	/**
	 * Set value of _name
	 * @param context
	 * @param _name
	 */
	public final void set_name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _name)
	{
		getMendixObject().setValue(context, MemberNames._name.toString(), _name);
	}

	/**
	 * @return value of Topic_Project
	 */
	public final main.proxies.Project getTopic_Project() throws com.mendix.core.CoreException
	{
		return getTopic_Project(getContext());
	}

	/**
	 * @param context
	 * @return value of Topic_Project
	 */
	public final main.proxies.Project getTopic_Project(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		main.proxies.Project result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Topic_Project.toString());
		if (identifier != null)
			result = main.proxies.Project.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Topic_Project
	 * @param topic_project
	 */
	public final void setTopic_Project(main.proxies.Project topic_project)
	{
		setTopic_Project(getContext(), topic_project);
	}

	/**
	 * Set value of Topic_Project
	 * @param context
	 * @param topic_project
	 */
	public final void setTopic_Project(com.mendix.systemwideinterfaces.core.IContext context, main.proxies.Project topic_project)
	{
		if (topic_project == null)
			getMendixObject().setValue(context, MemberNames.Topic_Project.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Topic_Project.toString(), topic_project.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return topicMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final pubsub.proxies.Topic that = (pubsub.proxies.Topic) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "PubSub.Topic";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
