// This file was generated by Mendix Modeler 7.21.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package gcpiot.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the GCPIoT module

	public static java.lang.String getLogNode()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("GCPIoT.LogNode");
	}

	public static java.lang.String getTempFilePath()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("GCPIoT.TempFilePath");
	}
}