// This file was generated by Mendix Modeler 7.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package bigquery.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the BigQuery module
	public static bigquery.proxies.BigQueryHelper dS_GetHelper(IContext context, main.proxies.Project _project)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Project", _project == null ? null : _project.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "BigQuery.DS_GetHelper", params);
			return result == null ? null : bigquery.proxies.BigQueryHelper.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_GetDatasets(IContext context, main.proxies.Project _project, bigquery.proxies.BigQueryHelper _bigQueryHelper)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Project", _project == null ? null : _project.getMendixObject());
			params.put("BigQueryHelper", _bigQueryHelper == null ? null : _bigQueryHelper.getMendixObject());
			Core.execute(context, "BigQuery.IVK_GetDatasets", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_RunQuery(IContext context, main.proxies.Project _project, bigquery.proxies.BigQueryHelper _bigQueryHelper)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Project", _project == null ? null : _project.getMendixObject());
			params.put("BigQueryHelper", _bigQueryHelper == null ? null : _bigQueryHelper.getMendixObject());
			Core.execute(context, "BigQuery.IVK_RunQuery", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}