// This file was generated by Mendix Modeler 7.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package main.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the Main module

	public static boolean getSubscribeOnStartup()
	{
		return (java.lang.Boolean)Core.getConfiguration().getConstantValue("Main.SubscribeOnStartup");
	}
}