// This file was generated by Mendix Modeler 7.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package gcp.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the GCP module

	public static java.lang.String getLogNodeName()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("GCP.LogNodeName");
	}
}