// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package gcp.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import gcp.impl.FileHelper;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class J_LoadCredentialFile extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __CredentialFile;
	private system.proxies.FileDocument CredentialFile;

	public J_LoadCredentialFile(IContext context, IMendixObject CredentialFile)
	{
		super(context);
		this.__CredentialFile = CredentialFile;
	}

	@Override
	public java.lang.String executeAction() throws Exception
	{
		this.CredentialFile = __CredentialFile == null ? null : system.proxies.FileDocument.initialize(getContext(), __CredentialFile);

		// BEGIN USER CODE
		return FileHelper.getProjectId(this.getContext(), __CredentialFile);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "J_LoadCredentialFile";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
