// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package gcp.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import gcp.impl.Logger;
import gcp.impl.SubscribeAgent;

public class J_StartSubscriberAgent extends CustomJavaAction<java.lang.Boolean>
{
	public J_StartSubscriberAgent(IContext context)
	{
		super(context);
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			SubscribeAgent agent = new SubscribeAgent();
			agent.initialize();
		}
		catch (Exception e)
		{
			Logger.error("There was a problem starting subscribe agent \r\n" + e.getMessage());
			return false;
		}
		Logger.info("Successfully started Subscribe Agent's activities");
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "J_StartSubscriberAgent";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
