// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package bigquery.proxies;

public class BigQueryHelper
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject bigQueryHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "BigQuery.BigQueryHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Query("Query"),
		Result("Result"),
		BigQueryHelper_Project("BigQuery.BigQueryHelper_Project");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public BigQueryHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "BigQuery.BigQueryHelper"));
	}

	protected BigQueryHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject bigQueryHelperMendixObject)
	{
		if (bigQueryHelperMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("BigQuery.BigQueryHelper", bigQueryHelperMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a BigQuery.BigQueryHelper");

		this.bigQueryHelperMendixObject = bigQueryHelperMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'BigQueryHelper.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static bigquery.proxies.BigQueryHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return bigquery.proxies.BigQueryHelper.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static bigquery.proxies.BigQueryHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new bigquery.proxies.BigQueryHelper(context, mendixObject);
	}

	public static bigquery.proxies.BigQueryHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return bigquery.proxies.BigQueryHelper.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Query
	 */
	public final java.lang.String getQuery()
	{
		return getQuery(getContext());
	}

	/**
	 * @param context
	 * @return value of Query
	 */
	public final java.lang.String getQuery(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Query.toString());
	}

	/**
	 * Set value of Query
	 * @param query
	 */
	public final void setQuery(java.lang.String query)
	{
		setQuery(getContext(), query);
	}

	/**
	 * Set value of Query
	 * @param context
	 * @param query
	 */
	public final void setQuery(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String query)
	{
		getMendixObject().setValue(context, MemberNames.Query.toString(), query);
	}

	/**
	 * @return value of Result
	 */
	public final java.lang.String getResult()
	{
		return getResult(getContext());
	}

	/**
	 * @param context
	 * @return value of Result
	 */
	public final java.lang.String getResult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Result.toString());
	}

	/**
	 * Set value of Result
	 * @param result
	 */
	public final void setResult(java.lang.String result)
	{
		setResult(getContext(), result);
	}

	/**
	 * Set value of Result
	 * @param context
	 * @param result
	 */
	public final void setResult(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String result)
	{
		getMendixObject().setValue(context, MemberNames.Result.toString(), result);
	}

	/**
	 * @return value of BigQueryHelper_Project
	 */
	public final main.proxies.Project getBigQueryHelper_Project() throws com.mendix.core.CoreException
	{
		return getBigQueryHelper_Project(getContext());
	}

	/**
	 * @param context
	 * @return value of BigQueryHelper_Project
	 */
	public final main.proxies.Project getBigQueryHelper_Project(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		main.proxies.Project result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BigQueryHelper_Project.toString());
		if (identifier != null)
			result = main.proxies.Project.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BigQueryHelper_Project
	 * @param bigqueryhelper_project
	 */
	public final void setBigQueryHelper_Project(main.proxies.Project bigqueryhelper_project)
	{
		setBigQueryHelper_Project(getContext(), bigqueryhelper_project);
	}

	/**
	 * Set value of BigQueryHelper_Project
	 * @param context
	 * @param bigqueryhelper_project
	 */
	public final void setBigQueryHelper_Project(com.mendix.systemwideinterfaces.core.IContext context, main.proxies.Project bigqueryhelper_project)
	{
		if (bigqueryhelper_project == null)
			getMendixObject().setValue(context, MemberNames.BigQueryHelper_Project.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BigQueryHelper_Project.toString(), bigqueryhelper_project.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return bigQueryHelperMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final bigquery.proxies.BigQueryHelper that = (bigquery.proxies.BigQueryHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "BigQuery.BigQueryHelper";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
