// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package bigquery.proxies;

public class DatasetType
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject datasetTypeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "BigQuery.DatasetType";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		DatasetType_BigQueryHelper("BigQuery.DatasetType_BigQueryHelper");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DatasetType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "BigQuery.DatasetType"));
	}

	protected DatasetType(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject datasetTypeMendixObject)
	{
		if (datasetTypeMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("BigQuery.DatasetType", datasetTypeMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a BigQuery.DatasetType");

		this.datasetTypeMendixObject = datasetTypeMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DatasetType.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static bigquery.proxies.DatasetType initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return bigquery.proxies.DatasetType.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static bigquery.proxies.DatasetType initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new bigquery.proxies.DatasetType(context, mendixObject);
	}

	public static bigquery.proxies.DatasetType load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return bigquery.proxies.DatasetType.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of DatasetType_BigQueryHelper
	 */
	public final bigquery.proxies.BigQueryHelper getDatasetType_BigQueryHelper() throws com.mendix.core.CoreException
	{
		return getDatasetType_BigQueryHelper(getContext());
	}

	/**
	 * @param context
	 * @return value of DatasetType_BigQueryHelper
	 */
	public final bigquery.proxies.BigQueryHelper getDatasetType_BigQueryHelper(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		bigquery.proxies.BigQueryHelper result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DatasetType_BigQueryHelper.toString());
		if (identifier != null)
			result = bigquery.proxies.BigQueryHelper.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DatasetType_BigQueryHelper
	 * @param datasettype_bigqueryhelper
	 */
	public final void setDatasetType_BigQueryHelper(bigquery.proxies.BigQueryHelper datasettype_bigqueryhelper)
	{
		setDatasetType_BigQueryHelper(getContext(), datasettype_bigqueryhelper);
	}

	/**
	 * Set value of DatasetType_BigQueryHelper
	 * @param context
	 * @param datasettype_bigqueryhelper
	 */
	public final void setDatasetType_BigQueryHelper(com.mendix.systemwideinterfaces.core.IContext context, bigquery.proxies.BigQueryHelper datasettype_bigqueryhelper)
	{
		if (datasettype_bigqueryhelper == null)
			getMendixObject().setValue(context, MemberNames.DatasetType_BigQueryHelper.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DatasetType_BigQueryHelper.toString(), datasettype_bigqueryhelper.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return datasetTypeMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final bigquery.proxies.DatasetType that = (bigquery.proxies.DatasetType) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "BigQuery.DatasetType";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
