// This file was generated by Mendix Modeler 7.21.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package gcpiot.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the GCPIoT module
	public static void aCo_SetProjectIdFromCredentialsFile(IContext context, gcpiot.proxies.Project _gCPCredentials)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("GCPCredentials", _gCPCredentials == null ? null : _gCPCredentials.getMendixObject());
			Core.execute(context, "GCPIoT.ACo_SetProjectIdFromCredentialsFile", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void eXAMPLE_Callback(IContext context, java.lang.String _attributes, java.lang.String _payload)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Attributes", _attributes);
			params.put("Payload", _payload);
			Core.execute(context, "GCPIoT.EXAMPLE_Callback", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void eXAMPLE_Publish(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "GCPIoT.EXAMPLE_Publish", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void eXAMPLE_Subscribe(IContext context, gcpiot.proxies.Project _gCPCredentials, java.lang.String _subscriptionName)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("GCPCredentials", _gCPCredentials == null ? null : _gCPCredentials.getMendixObject());
			params.put("SubscriptionName", _subscriptionName);
			Core.execute(context, "GCPIoT.EXAMPLE_Subscribe", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void eXAMPLE_Unsubscribe(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "GCPIoT.EXAMPLE_Unsubscribe", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}