// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package main.proxies;

public class Data
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Main.Data";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Time("Time"),
		Temp("Temp"),
		TempNum("TempNum"),
		Data_Subscription("Main.Data_Subscription"),
		Data_Device("Main.Data_Device");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Data(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Main.Data"));
	}

	protected Data(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dataMendixObject)
	{
		if (dataMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Main.Data", dataMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Main.Data");

		this.dataMendixObject = dataMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Data.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static main.proxies.Data initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return main.proxies.Data.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static main.proxies.Data initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new main.proxies.Data(context, mendixObject);
	}

	public static main.proxies.Data load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return main.proxies.Data.initialize(context, mendixObject);
	}

	public static java.util.List<main.proxies.Data> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<main.proxies.Data> result = new java.util.ArrayList<main.proxies.Data>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Main.Data" + xpathConstraint))
			result.add(main.proxies.Data.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Time
	 */
	public final java.lang.String getTime()
	{
		return getTime(getContext());
	}

	/**
	 * @param context
	 * @return value of Time
	 */
	public final java.lang.String getTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Time.toString());
	}

	/**
	 * Set value of Time
	 * @param time
	 */
	public final void setTime(java.lang.String time)
	{
		setTime(getContext(), time);
	}

	/**
	 * Set value of Time
	 * @param context
	 * @param time
	 */
	public final void setTime(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String time)
	{
		getMendixObject().setValue(context, MemberNames.Time.toString(), time);
	}

	/**
	 * @return value of Temp
	 */
	public final java.lang.String getTemp()
	{
		return getTemp(getContext());
	}

	/**
	 * @param context
	 * @return value of Temp
	 */
	public final java.lang.String getTemp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Temp.toString());
	}

	/**
	 * Set value of Temp
	 * @param temp
	 */
	public final void setTemp(java.lang.String temp)
	{
		setTemp(getContext(), temp);
	}

	/**
	 * Set value of Temp
	 * @param context
	 * @param temp
	 */
	public final void setTemp(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String temp)
	{
		getMendixObject().setValue(context, MemberNames.Temp.toString(), temp);
	}

	/**
	 * @return value of TempNum
	 */
	public final java.math.BigDecimal getTempNum()
	{
		return getTempNum(getContext());
	}

	/**
	 * @param context
	 * @return value of TempNum
	 */
	public final java.math.BigDecimal getTempNum(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TempNum.toString());
	}

	/**
	 * Set value of TempNum
	 * @param tempnum
	 */
	public final void setTempNum(java.math.BigDecimal tempnum)
	{
		setTempNum(getContext(), tempnum);
	}

	/**
	 * Set value of TempNum
	 * @param context
	 * @param tempnum
	 */
	public final void setTempNum(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal tempnum)
	{
		getMendixObject().setValue(context, MemberNames.TempNum.toString(), tempnum);
	}

	/**
	 * @return value of Data_Subscription
	 */
	public final main.proxies.Subscription getData_Subscription() throws com.mendix.core.CoreException
	{
		return getData_Subscription(getContext());
	}

	/**
	 * @param context
	 * @return value of Data_Subscription
	 */
	public final main.proxies.Subscription getData_Subscription(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		main.proxies.Subscription result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Data_Subscription.toString());
		if (identifier != null)
			result = main.proxies.Subscription.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Data_Subscription
	 * @param data_subscription
	 */
	public final void setData_Subscription(main.proxies.Subscription data_subscription)
	{
		setData_Subscription(getContext(), data_subscription);
	}

	/**
	 * Set value of Data_Subscription
	 * @param context
	 * @param data_subscription
	 */
	public final void setData_Subscription(com.mendix.systemwideinterfaces.core.IContext context, main.proxies.Subscription data_subscription)
	{
		if (data_subscription == null)
			getMendixObject().setValue(context, MemberNames.Data_Subscription.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Data_Subscription.toString(), data_subscription.getMendixObject().getId());
	}

	/**
	 * @return value of Data_Device
	 */
	public final main.proxies.Device getData_Device() throws com.mendix.core.CoreException
	{
		return getData_Device(getContext());
	}

	/**
	 * @param context
	 * @return value of Data_Device
	 */
	public final main.proxies.Device getData_Device(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		main.proxies.Device result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Data_Device.toString());
		if (identifier != null)
			result = main.proxies.Device.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Data_Device
	 * @param data_device
	 */
	public final void setData_Device(main.proxies.Device data_device)
	{
		setData_Device(getContext(), data_device);
	}

	/**
	 * Set value of Data_Device
	 * @param context
	 * @param data_device
	 */
	public final void setData_Device(com.mendix.systemwideinterfaces.core.IContext context, main.proxies.Device data_device)
	{
		if (data_device == null)
			getMendixObject().setValue(context, MemberNames.Data_Device.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Data_Device.toString(), data_device.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dataMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final main.proxies.Data that = (main.proxies.Data) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Main.Data";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
