// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package main.proxies;

public class Device
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject deviceMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Main.Device";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DeviceName("DeviceName"),
		DeviceId("DeviceId"),
		Device_Subscription("Main.Device_Subscription");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Device(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Main.Device"));
	}

	protected Device(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject deviceMendixObject)
	{
		if (deviceMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Main.Device", deviceMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Main.Device");

		this.deviceMendixObject = deviceMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Device.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static main.proxies.Device initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return main.proxies.Device.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static main.proxies.Device initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new main.proxies.Device(context, mendixObject);
	}

	public static main.proxies.Device load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return main.proxies.Device.initialize(context, mendixObject);
	}

	public static java.util.List<main.proxies.Device> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<main.proxies.Device> result = new java.util.ArrayList<main.proxies.Device>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Main.Device" + xpathConstraint))
			result.add(main.proxies.Device.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of DeviceName
	 */
	public final java.lang.String getDeviceName()
	{
		return getDeviceName(getContext());
	}

	/**
	 * @param context
	 * @return value of DeviceName
	 */
	public final java.lang.String getDeviceName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DeviceName.toString());
	}

	/**
	 * Set value of DeviceName
	 * @param devicename
	 */
	public final void setDeviceName(java.lang.String devicename)
	{
		setDeviceName(getContext(), devicename);
	}

	/**
	 * Set value of DeviceName
	 * @param context
	 * @param devicename
	 */
	public final void setDeviceName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String devicename)
	{
		getMendixObject().setValue(context, MemberNames.DeviceName.toString(), devicename);
	}

	/**
	 * @return value of DeviceId
	 */
	public final java.lang.String getDeviceId()
	{
		return getDeviceId(getContext());
	}

	/**
	 * @param context
	 * @return value of DeviceId
	 */
	public final java.lang.String getDeviceId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DeviceId.toString());
	}

	/**
	 * Set value of DeviceId
	 * @param deviceid
	 */
	public final void setDeviceId(java.lang.String deviceid)
	{
		setDeviceId(getContext(), deviceid);
	}

	/**
	 * Set value of DeviceId
	 * @param context
	 * @param deviceid
	 */
	public final void setDeviceId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String deviceid)
	{
		getMendixObject().setValue(context, MemberNames.DeviceId.toString(), deviceid);
	}

	/**
	 * @return value of Device_Subscription
	 */
	public final main.proxies.Subscription getDevice_Subscription() throws com.mendix.core.CoreException
	{
		return getDevice_Subscription(getContext());
	}

	/**
	 * @param context
	 * @return value of Device_Subscription
	 */
	public final main.proxies.Subscription getDevice_Subscription(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		main.proxies.Subscription result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Device_Subscription.toString());
		if (identifier != null)
			result = main.proxies.Subscription.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Device_Subscription
	 * @param device_subscription
	 */
	public final void setDevice_Subscription(main.proxies.Subscription device_subscription)
	{
		setDevice_Subscription(getContext(), device_subscription);
	}

	/**
	 * Set value of Device_Subscription
	 * @param context
	 * @param device_subscription
	 */
	public final void setDevice_Subscription(com.mendix.systemwideinterfaces.core.IContext context, main.proxies.Subscription device_subscription)
	{
		if (device_subscription == null)
			getMendixObject().setValue(context, MemberNames.Device_Subscription.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Device_Subscription.toString(), device_subscription.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return deviceMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final main.proxies.Device that = (main.proxies.Device) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Main.Device";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
