// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package main.proxies;

public class PubMessage
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject pubMessageMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Main.PubMessage";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TopicName("TopicName"),
		Message("Message"),
		MessageNumber("MessageNumber");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PubMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Main.PubMessage"));
	}

	protected PubMessage(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject pubMessageMendixObject)
	{
		if (pubMessageMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Main.PubMessage", pubMessageMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Main.PubMessage");

		this.pubMessageMendixObject = pubMessageMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'PubMessage.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static main.proxies.PubMessage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return main.proxies.PubMessage.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static main.proxies.PubMessage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new main.proxies.PubMessage(context, mendixObject);
	}

	public static main.proxies.PubMessage load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return main.proxies.PubMessage.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of TopicName
	 */
	public final java.lang.String getTopicName()
	{
		return getTopicName(getContext());
	}

	/**
	 * @param context
	 * @return value of TopicName
	 */
	public final java.lang.String getTopicName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TopicName.toString());
	}

	/**
	 * Set value of TopicName
	 * @param topicname
	 */
	public final void setTopicName(java.lang.String topicname)
	{
		setTopicName(getContext(), topicname);
	}

	/**
	 * Set value of TopicName
	 * @param context
	 * @param topicname
	 */
	public final void setTopicName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String topicname)
	{
		getMendixObject().setValue(context, MemberNames.TopicName.toString(), topicname);
	}

	/**
	 * @return value of Message
	 */
	public final java.lang.String getMessage()
	{
		return getMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of Message
	 */
	public final java.lang.String getMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Message.toString());
	}

	/**
	 * Set value of Message
	 * @param message
	 */
	public final void setMessage(java.lang.String message)
	{
		setMessage(getContext(), message);
	}

	/**
	 * Set value of Message
	 * @param context
	 * @param message
	 */
	public final void setMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String message)
	{
		getMendixObject().setValue(context, MemberNames.Message.toString(), message);
	}

	/**
	 * @return value of MessageNumber
	 */
	public final java.lang.Integer getMessageNumber()
	{
		return getMessageNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of MessageNumber
	 */
	public final java.lang.Integer getMessageNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MessageNumber.toString());
	}

	/**
	 * Set value of MessageNumber
	 * @param messagenumber
	 */
	public final void setMessageNumber(java.lang.Integer messagenumber)
	{
		setMessageNumber(getContext(), messagenumber);
	}

	/**
	 * Set value of MessageNumber
	 * @param context
	 * @param messagenumber
	 */
	public final void setMessageNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer messagenumber)
	{
		getMendixObject().setValue(context, MemberNames.MessageNumber.toString(), messagenumber);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return pubMessageMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final main.proxies.PubMessage that = (main.proxies.PubMessage) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Main.PubMessage";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
