// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package iot.proxies;

public class Gateway
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject gatewayMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "IoT.Gateway";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Gateway_Registry("IoT.Gateway_Registry");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Gateway(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "IoT.Gateway"));
	}

	protected Gateway(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject gatewayMendixObject)
	{
		if (gatewayMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("IoT.Gateway", gatewayMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a IoT.Gateway");

		this.gatewayMendixObject = gatewayMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Gateway.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static iot.proxies.Gateway initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return iot.proxies.Gateway.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static iot.proxies.Gateway initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new iot.proxies.Gateway(context, mendixObject);
	}

	public static iot.proxies.Gateway load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return iot.proxies.Gateway.initialize(context, mendixObject);
	}

	public static java.util.List<iot.proxies.Gateway> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<iot.proxies.Gateway> result = new java.util.ArrayList<iot.proxies.Gateway>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//IoT.Gateway" + xpathConstraint))
			result.add(iot.proxies.Gateway.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Gateway_Registry
	 */
	public final iot.proxies.Registry getGateway_Registry() throws com.mendix.core.CoreException
	{
		return getGateway_Registry(getContext());
	}

	/**
	 * @param context
	 * @return value of Gateway_Registry
	 */
	public final iot.proxies.Registry getGateway_Registry(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		iot.proxies.Registry result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Gateway_Registry.toString());
		if (identifier != null)
			result = iot.proxies.Registry.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Gateway_Registry
	 * @param gateway_registry
	 */
	public final void setGateway_Registry(iot.proxies.Registry gateway_registry)
	{
		setGateway_Registry(getContext(), gateway_registry);
	}

	/**
	 * Set value of Gateway_Registry
	 * @param context
	 * @param gateway_registry
	 */
	public final void setGateway_Registry(com.mendix.systemwideinterfaces.core.IContext context, iot.proxies.Registry gateway_registry)
	{
		if (gateway_registry == null)
			getMendixObject().setValue(context, MemberNames.Gateway_Registry.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Gateway_Registry.toString(), gateway_registry.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return gatewayMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final iot.proxies.Gateway that = (iot.proxies.Gateway) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "IoT.Gateway";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
