// This file was generated by Mendix Modeler 7.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package iot.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the IoT module
	public static void iVK_SendCommand(IContext context, iot.proxies.CommandHelper _commandHelper)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("CommandHelper", _commandHelper == null ? null : _commandHelper.getMendixObject());
			Core.execute(context, "IoT.IVK_SendCommand", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_ShowNewCommand(IContext context, iot.proxies.Device _device, iot.proxies.Registry _registry)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Device", _device == null ? null : _device.getMendixObject());
			params.put("Registry", _registry == null ? null : _registry.getMendixObject());
			Core.execute(context, "IoT.IVK_ShowNewCommand", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_ShowNewDevice(IContext context, iot.proxies.Registry _registry, main.proxies.Project _project)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Registry", _registry == null ? null : _registry.getMendixObject());
			params.put("Project", _project == null ? null : _project.getMendixObject());
			Core.execute(context, "IoT.IVK_ShowNewDevice", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_ShowNewRegistry(IContext context, main.proxies.Project _project)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Project", _project == null ? null : _project.getMendixObject());
			Core.execute(context, "IoT.IVK_ShowNewRegistry", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}