// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package gcp.proxies;

public class Credential extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "GCP.Credential";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ProjectId("ProjectId"),
		IsLoaded("IsLoaded"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Credential(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "GCP.Credential"));
	}

	protected Credential(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject credentialMendixObject)
	{
		super(context, credentialMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("GCP.Credential", credentialMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a GCP.Credential");
	}

	/**
	 * @deprecated Use 'Credential.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static gcp.proxies.Credential initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return gcp.proxies.Credential.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static gcp.proxies.Credential initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new gcp.proxies.Credential(context, mendixObject);
	}

	public static gcp.proxies.Credential load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return gcp.proxies.Credential.initialize(context, mendixObject);
	}

	public static java.util.List<gcp.proxies.Credential> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<gcp.proxies.Credential> result = new java.util.ArrayList<gcp.proxies.Credential>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//GCP.Credential" + xpathConstraint))
			result.add(gcp.proxies.Credential.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of ProjectId
	 */
	public final java.lang.String getProjectId()
	{
		return getProjectId(getContext());
	}

	/**
	 * @param context
	 * @return value of ProjectId
	 */
	public final java.lang.String getProjectId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProjectId.toString());
	}

	/**
	 * Set value of ProjectId
	 * @param projectid
	 */
	public final void setProjectId(java.lang.String projectid)
	{
		setProjectId(getContext(), projectid);
	}

	/**
	 * Set value of ProjectId
	 * @param context
	 * @param projectid
	 */
	public final void setProjectId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String projectid)
	{
		getMendixObject().setValue(context, MemberNames.ProjectId.toString(), projectid);
	}

	/**
	 * @return value of IsLoaded
	 */
	public final java.lang.Boolean getIsLoaded()
	{
		return getIsLoaded(getContext());
	}

	/**
	 * @param context
	 * @return value of IsLoaded
	 */
	public final java.lang.Boolean getIsLoaded(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsLoaded.toString());
	}

	/**
	 * Set value of IsLoaded
	 * @param isloaded
	 */
	public final void setIsLoaded(java.lang.Boolean isloaded)
	{
		setIsLoaded(getContext(), isloaded);
	}

	/**
	 * Set value of IsLoaded
	 * @param context
	 * @param isloaded
	 */
	public final void setIsLoaded(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isloaded)
	{
		getMendixObject().setValue(context, MemberNames.IsLoaded.toString(), isloaded);
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final gcp.proxies.Credential that = (gcp.proxies.Credential) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "GCP.Credential";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
