// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package gcpiot.proxies;

public class Attributes
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject attributesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "GCPIoT.Attributes";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ProjectId("ProjectId"),
		DeviceId("DeviceId"),
		DeviceNumId("DeviceNumId"),
		DeviceRegistryLocation("DeviceRegistryLocation"),
		DeviceRegistryId("DeviceRegistryId"),
		SubFolder("SubFolder"),
		SubscriptionId("SubscriptionId");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Attributes(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "GCPIoT.Attributes"));
	}

	protected Attributes(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject attributesMendixObject)
	{
		if (attributesMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("GCPIoT.Attributes", attributesMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a GCPIoT.Attributes");

		this.attributesMendixObject = attributesMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Attributes.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static gcpiot.proxies.Attributes initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return gcpiot.proxies.Attributes.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static gcpiot.proxies.Attributes initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new gcpiot.proxies.Attributes(context, mendixObject);
	}

	public static gcpiot.proxies.Attributes load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return gcpiot.proxies.Attributes.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ProjectId
	 */
	public final java.lang.String getProjectId()
	{
		return getProjectId(getContext());
	}

	/**
	 * @param context
	 * @return value of ProjectId
	 */
	public final java.lang.String getProjectId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProjectId.toString());
	}

	/**
	 * Set value of ProjectId
	 * @param projectid
	 */
	public final void setProjectId(java.lang.String projectid)
	{
		setProjectId(getContext(), projectid);
	}

	/**
	 * Set value of ProjectId
	 * @param context
	 * @param projectid
	 */
	public final void setProjectId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String projectid)
	{
		getMendixObject().setValue(context, MemberNames.ProjectId.toString(), projectid);
	}

	/**
	 * @return value of DeviceId
	 */
	public final java.lang.String getDeviceId()
	{
		return getDeviceId(getContext());
	}

	/**
	 * @param context
	 * @return value of DeviceId
	 */
	public final java.lang.String getDeviceId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DeviceId.toString());
	}

	/**
	 * Set value of DeviceId
	 * @param deviceid
	 */
	public final void setDeviceId(java.lang.String deviceid)
	{
		setDeviceId(getContext(), deviceid);
	}

	/**
	 * Set value of DeviceId
	 * @param context
	 * @param deviceid
	 */
	public final void setDeviceId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String deviceid)
	{
		getMendixObject().setValue(context, MemberNames.DeviceId.toString(), deviceid);
	}

	/**
	 * @return value of DeviceNumId
	 */
	public final java.lang.String getDeviceNumId()
	{
		return getDeviceNumId(getContext());
	}

	/**
	 * @param context
	 * @return value of DeviceNumId
	 */
	public final java.lang.String getDeviceNumId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DeviceNumId.toString());
	}

	/**
	 * Set value of DeviceNumId
	 * @param devicenumid
	 */
	public final void setDeviceNumId(java.lang.String devicenumid)
	{
		setDeviceNumId(getContext(), devicenumid);
	}

	/**
	 * Set value of DeviceNumId
	 * @param context
	 * @param devicenumid
	 */
	public final void setDeviceNumId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String devicenumid)
	{
		getMendixObject().setValue(context, MemberNames.DeviceNumId.toString(), devicenumid);
	}

	/**
	 * @return value of DeviceRegistryLocation
	 */
	public final java.lang.String getDeviceRegistryLocation()
	{
		return getDeviceRegistryLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of DeviceRegistryLocation
	 */
	public final java.lang.String getDeviceRegistryLocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DeviceRegistryLocation.toString());
	}

	/**
	 * Set value of DeviceRegistryLocation
	 * @param deviceregistrylocation
	 */
	public final void setDeviceRegistryLocation(java.lang.String deviceregistrylocation)
	{
		setDeviceRegistryLocation(getContext(), deviceregistrylocation);
	}

	/**
	 * Set value of DeviceRegistryLocation
	 * @param context
	 * @param deviceregistrylocation
	 */
	public final void setDeviceRegistryLocation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String deviceregistrylocation)
	{
		getMendixObject().setValue(context, MemberNames.DeviceRegistryLocation.toString(), deviceregistrylocation);
	}

	/**
	 * @return value of DeviceRegistryId
	 */
	public final java.lang.String getDeviceRegistryId()
	{
		return getDeviceRegistryId(getContext());
	}

	/**
	 * @param context
	 * @return value of DeviceRegistryId
	 */
	public final java.lang.String getDeviceRegistryId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DeviceRegistryId.toString());
	}

	/**
	 * Set value of DeviceRegistryId
	 * @param deviceregistryid
	 */
	public final void setDeviceRegistryId(java.lang.String deviceregistryid)
	{
		setDeviceRegistryId(getContext(), deviceregistryid);
	}

	/**
	 * Set value of DeviceRegistryId
	 * @param context
	 * @param deviceregistryid
	 */
	public final void setDeviceRegistryId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String deviceregistryid)
	{
		getMendixObject().setValue(context, MemberNames.DeviceRegistryId.toString(), deviceregistryid);
	}

	/**
	 * @return value of SubFolder
	 */
	public final java.lang.String getSubFolder()
	{
		return getSubFolder(getContext());
	}

	/**
	 * @param context
	 * @return value of SubFolder
	 */
	public final java.lang.String getSubFolder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SubFolder.toString());
	}

	/**
	 * Set value of SubFolder
	 * @param subfolder
	 */
	public final void setSubFolder(java.lang.String subfolder)
	{
		setSubFolder(getContext(), subfolder);
	}

	/**
	 * Set value of SubFolder
	 * @param context
	 * @param subfolder
	 */
	public final void setSubFolder(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String subfolder)
	{
		getMendixObject().setValue(context, MemberNames.SubFolder.toString(), subfolder);
	}

	/**
	 * @return value of SubscriptionId
	 */
	public final java.lang.String getSubscriptionId()
	{
		return getSubscriptionId(getContext());
	}

	/**
	 * @param context
	 * @return value of SubscriptionId
	 */
	public final java.lang.String getSubscriptionId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SubscriptionId.toString());
	}

	/**
	 * Set value of SubscriptionId
	 * @param subscriptionid
	 */
	public final void setSubscriptionId(java.lang.String subscriptionid)
	{
		setSubscriptionId(getContext(), subscriptionid);
	}

	/**
	 * Set value of SubscriptionId
	 * @param context
	 * @param subscriptionid
	 */
	public final void setSubscriptionId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String subscriptionid)
	{
		getMendixObject().setValue(context, MemberNames.SubscriptionId.toString(), subscriptionid);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return attributesMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final gcpiot.proxies.Attributes that = (gcpiot.proxies.Attributes) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "GCPIoT.Attributes";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
