// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package gcpiot.proxies;

public class Project extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "GCPIoT.Project";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		projectId("projectId"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Project(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "GCPIoT.Project"));
	}

	protected Project(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject projectMendixObject)
	{
		super(context, projectMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("GCPIoT.Project", projectMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a GCPIoT.Project");
	}

	/**
	 * @deprecated Use 'Project.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static gcpiot.proxies.Project initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return gcpiot.proxies.Project.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static gcpiot.proxies.Project initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new gcpiot.proxies.Project(context, mendixObject);
	}

	public static gcpiot.proxies.Project load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return gcpiot.proxies.Project.initialize(context, mendixObject);
	}

	public static java.util.List<gcpiot.proxies.Project> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<gcpiot.proxies.Project> result = new java.util.ArrayList<gcpiot.proxies.Project>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//GCPIoT.Project" + xpathConstraint))
			result.add(gcpiot.proxies.Project.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of projectId
	 */
	public final java.lang.String getprojectId()
	{
		return getprojectId(getContext());
	}

	/**
	 * @param context
	 * @return value of projectId
	 */
	public final java.lang.String getprojectId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.projectId.toString());
	}

	/**
	 * Set value of projectId
	 * @param projectid
	 */
	public final void setprojectId(java.lang.String projectid)
	{
		setprojectId(getContext(), projectid);
	}

	/**
	 * Set value of projectId
	 * @param context
	 * @param projectid
	 */
	public final void setprojectId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String projectid)
	{
		getMendixObject().setValue(context, MemberNames.projectId.toString(), projectid);
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final gcpiot.proxies.Project that = (gcpiot.proxies.Project) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "GCPIoT.Project";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
