// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package chart.proxies;

public class Chart
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject chartMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Chart.Chart";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Chart_DataSet("Chart.Chart_DataSet"),
		Chart_Subscription("Chart.Chart_Subscription");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Chart(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Chart.Chart"));
	}

	protected Chart(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject chartMendixObject)
	{
		if (chartMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Chart.Chart", chartMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Chart.Chart");

		this.chartMendixObject = chartMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Chart.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static chart.proxies.Chart initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return chart.proxies.Chart.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static chart.proxies.Chart initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new chart.proxies.Chart(context, mendixObject);
	}

	public static chart.proxies.Chart load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return chart.proxies.Chart.initialize(context, mendixObject);
	}

	public static java.util.List<chart.proxies.Chart> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<chart.proxies.Chart> result = new java.util.ArrayList<chart.proxies.Chart>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Chart.Chart" + xpathConstraint))
			result.add(chart.proxies.Chart.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Chart_DataSet
	 */
	public final java.util.List<chart.proxies.DataSet> getChart_DataSet() throws com.mendix.core.CoreException
	{
		return getChart_DataSet(getContext());
	}

	/**
	 * @param context
	 * @return value of Chart_DataSet
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<chart.proxies.DataSet> getChart_DataSet(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<chart.proxies.DataSet> result = new java.util.ArrayList<chart.proxies.DataSet>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Chart_DataSet.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(chart.proxies.DataSet.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of Chart_DataSet
	 * @param chart_dataset
	 */
	public final void setChart_DataSet(java.util.List<chart.proxies.DataSet> chart_dataset)
	{
		setChart_DataSet(getContext(), chart_dataset);
	}

	/**
	 * Set value of Chart_DataSet
	 * @param context
	 * @param chart_dataset
	 */
	public final void setChart_DataSet(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<chart.proxies.DataSet> chart_dataset)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (chart.proxies.DataSet proxyObject : chart_dataset)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.Chart_DataSet.toString(), identifiers);
	}

	/**
	 * @return value of Chart_Subscription
	 */
	public final main.proxies.Subscription getChart_Subscription() throws com.mendix.core.CoreException
	{
		return getChart_Subscription(getContext());
	}

	/**
	 * @param context
	 * @return value of Chart_Subscription
	 */
	public final main.proxies.Subscription getChart_Subscription(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		main.proxies.Subscription result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Chart_Subscription.toString());
		if (identifier != null)
			result = main.proxies.Subscription.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Chart_Subscription
	 * @param chart_subscription
	 */
	public final void setChart_Subscription(main.proxies.Subscription chart_subscription)
	{
		setChart_Subscription(getContext(), chart_subscription);
	}

	/**
	 * Set value of Chart_Subscription
	 * @param context
	 * @param chart_subscription
	 */
	public final void setChart_Subscription(com.mendix.systemwideinterfaces.core.IContext context, main.proxies.Subscription chart_subscription)
	{
		if (chart_subscription == null)
			getMendixObject().setValue(context, MemberNames.Chart_Subscription.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Chart_Subscription.toString(), chart_subscription.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return chartMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final chart.proxies.Chart that = (chart.proxies.Chart) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Chart.Chart";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
