// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package gcpiot.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import gcpiot.impl.FileHelper;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class getProjectId extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __CredentialsFile;
	private gcpiot.proxies.GCPCredentials CredentialsFile;

	public getProjectId(IContext context, IMendixObject CredentialsFile)
	{
		super(context);
		this.__CredentialsFile = CredentialsFile;
	}

	@Override
	public java.lang.String executeAction() throws Exception
	{
		this.CredentialsFile = __CredentialsFile == null ? null : gcpiot.proxies.GCPCredentials.initialize(getContext(), __CredentialsFile);

		// BEGIN USER CODE
		return FileHelper.getProjectId(this.getContext(), __CredentialsFile);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "getProjectId";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
