// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package gcpiot.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Subscribes to Google Pub/Sub Subscription using sub name and JSON credentials file (https://cloud.google.com/docs/authentication/production#creating_a_service_account)
 * 
 * If you do not want to handle failures, specify a Microflow for OnFailure that does nothing
 * 
 * OnMessage and OnFailure Microflows are called asynchronously with two String parameters
 * "Attributes" and "Payload" See "EXAMPLE_Callback" for example
 * 
 * Returns String of ProjectId from Credentials file for confirmation
 * 
 * See example "EXAMPLE_Subscribe"
 */
public class publishToGCPTopic extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __CredentialsFile;
	private system.proxies.FileDocument CredentialsFile;
	private java.lang.String TopicId;
	private java.lang.String Payload;

	public publishToGCPTopic(IContext context, IMendixObject CredentialsFile, java.lang.String TopicId, java.lang.String Payload)
	{
		super(context);
		this.__CredentialsFile = CredentialsFile;
		this.TopicId = TopicId;
		this.Payload = Payload;
	}

	@Override
	public java.lang.String executeAction() throws Exception
	{
		this.CredentialsFile = __CredentialsFile == null ? null : system.proxies.FileDocument.initialize(getContext(), __CredentialsFile);

		// BEGIN USER CODE
		return "Not implemented yet!";
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "publishToGCPTopic";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
