// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package gcpiot.actions;

import java.io.InputStream;
import com.google.api.core.ApiFuture;
import com.google.api.core.ApiFutureCallback;
import com.google.api.core.ApiFutures;
import com.google.api.gax.rpc.ApiException;
import com.google.common.util.concurrent.MoreExecutors;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import gcpiot.impl.FileHelper;
import gcpiot.impl.GCPAgent;
import gcpiot.impl.GCPPublisher;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Subscribes to Google Pub/Sub Subscription using sub name and JSON credentials file (https://cloud.google.com/docs/authentication/production#creating_a_service_account)
 * 
 * If you do not want to handle failures, specify a Microflow for OnFailure that does nothing
 * 
 * OnMessage and OnFailure Microflows are called asynchronously with two String parameters
 * "Attributes" and "Payload" See "EXAMPLE_Callback" for example
 * 
 * Returns String of ProjectId from Credentials file for confirmation
 * 
 * See example "EXAMPLE_Subscribe"
 */
public class publishToGCPTopic extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __CredentialsFile;
	private system.proxies.FileDocument CredentialsFile;
	private java.lang.String TopicId;
	private java.lang.String Payload;

	public publishToGCPTopic(IContext context, IMendixObject CredentialsFile, java.lang.String TopicId, java.lang.String Payload)
	{
		super(context);
		this.__CredentialsFile = CredentialsFile;
		this.TopicId = TopicId;
		this.Payload = Payload;
	}

	@Override
	public java.lang.String executeAction() throws Exception
	{
		this.CredentialsFile = __CredentialsFile == null ? null : system.proxies.FileDocument.initialize(getContext(), __CredentialsFile);

		// BEGIN USER CODE
		GCPAgent agent = new GCPAgent();
		String projectId = FileHelper.getProjectId(this.getContext(), __CredentialsFile);
		ApiFuture<String> future = null;

		if (agent.getPublisher(TopicId + "-" + projectId) == null)
		{
			agent.initialize();
			InputStream credentialsInputFile = FileHelper.getCredentialsFileStream(this.getContext(),__CredentialsFile);		
			GCPPublisher publisher = new GCPPublisher(TopicId + "-" + projectId, TopicId, projectId,credentialsInputFile );
			agent.pushPub(publisher);
			Core.getLogger(GCPAgent.LogNode).debug("Listening to: "+agent.getGcpSubscribers().size() + " Subscriptions");
		}
		else
		{
			Core.getLogger(GCPAgent.LogNode).info(TopicId + "-" + projectId + " already a publisher");
		}

		try {
			GCPPublisher p = agent.getPublisher(TopicId + "-" + projectId);
			Core.getLogger(GCPAgent.LogNode).debug("Publisher: " + p.getPublisherId());

			if(p!=null)
			{
				future = p.publish(Payload);
				ApiFutures.addCallback(
						future,
						new ApiFutureCallback<String>() {

							@Override
							public void onFailure(Throwable throwable) {
								if (throwable instanceof ApiException) {
									ApiException apiException = ((ApiException) throwable);
									// details on the API exception
									Core.getLogger(GCPAgent.LogNode).error(apiException.getStatusCode().getCode());
									Core.getLogger(GCPAgent.LogNode).error(apiException.isRetryable());
								}
								Core.getLogger(GCPAgent.LogNode).error("Error publishing message : " + Payload);
							}

							@Override
							public void onSuccess(String messageId) {
								// Once published, returns server-assigned message ids (unique within the topic)
								Core.getLogger(GCPAgent.LogNode).debug("PUBLISH: Success - " + messageId);
							}
						},
						MoreExecutors.directExecutor());
			}
		}
		catch(Exception e) {
			Core.getLogger(GCPAgent.LogNode).error(e.getStackTrace());
		}

		return future.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "publishToGCPTopic";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
