// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package gcpiot.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import gcpiot.impl.GCPAgent;

/**
 * Starts Subscribe agent for subscribing to Pub/Sub subcriptions for Google. To be run after startup
 */
public class startGCPAgent extends CustomJavaAction<java.lang.Boolean>
{
	public startGCPAgent(IContext context)
	{
		super(context);
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		GCPAgent agent = new GCPAgent();
		agent.initialize();

		Core.getLogger(GCPAgent.LogNode).info("Listening to: "+agent.getGcpSubscribers().size() + " Subscriptions");
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "startGCPAgent";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
