// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package gcpiot.actions;

import java.util.Map;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import gcpiot.impl.GCPAgent;
import gcpiot.impl.GCPSubscriber;

public class stopGCPAgent extends CustomJavaAction<java.lang.Boolean>
{
	public stopGCPAgent(IContext context)
	{
		super(context);
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		GCPAgent agent = new GCPAgent();
		agent.initialize();
		Map<String, GCPSubscriber> gsubs = agent.getGcpSubscribers();
		
		for (String key : gsubs.keySet())
		{
		    GCPSubscriber sub = gsubs.get(key);
		    sub.stop();
		    agent.pullSub(key);
		}

		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "stopGCPAgent";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
