// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package gcpiot.actions;

import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import gcpiot.impl.Agent;
import gcpiot.impl.GCPPublisher;
import gcpiot.impl.GCPSubscriber;

/**
 * Terminates all subscribers and stops Subscribe agent for subscribing to Pub/Sub subcriptions for Google. To be run before shutdown
 */
public class stopGCPAgent extends CustomJavaAction<java.lang.Boolean>
{
	public stopGCPAgent(IContext context)
	{
		super(context);
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		Agent agent = new Agent();
		agent.initialize();
		Map<String, GCPSubscriber> gsubs = agent.getGcpSubscribers();
		
		for (String key : gsubs.keySet())
		{
		    GCPSubscriber sub = gsubs.get(key);
		    sub.stop();
		    agent.pullSub(key);
		}
		
		Map<String, GCPPublisher> gpubs = agent.getGcpPublishers();
		
		for (String key : gpubs.keySet())
		{
		    GCPPublisher pub = gpubs.get(key);
		    pub.stop();
		    agent.pullPub(key);
		}
		Core.getLogger(Agent.LogNode).info("Succesffully stopped GCP Agent's activities");

		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "stopGCPAgent";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
