// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package gcpiot.actions;

import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import gcpiot.impl.Agent;
import gcpiot.impl.GCPSubscriber;

/**
 * Unsubscribes to Google Pub/Sub Subscription using sub name project id. See example "EXAMPLE_Unsubscribe"
 */
public class unsubscribeFromGCPSub extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String SubscriptionId;
	private java.lang.String ProjectId;

	public unsubscribeFromGCPSub(IContext context, java.lang.String SubscriptionId, java.lang.String ProjectId)
	{
		super(context);
		this.SubscriptionId = SubscriptionId;
		this.ProjectId = ProjectId;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		Core.getLogger(Agent.LogNode).debug("Trying to unsubscribe: " + SubscriptionId);
		Agent agent = new Agent();
		agent.initialize();
		Map<String, GCPSubscriber> gsubs = agent.getGcpSubscribers();
		GCPSubscriber sub = gsubs.get(SubscriptionId+"-"+ProjectId);
		
		if(sub == null)
		{
			Core.getLogger(Agent.LogNode).warn("No Subscriber found!");
		}
		else
		{
			Core.getLogger(Agent.LogNode).debug("Subscriber to stop: " + sub.getSubscriber());
		}

		try {
			Core.getLogger(Agent.LogNode).debug("Trying to stop: " + sub.getSubscriber());
			sub.stop();
		}
		catch(Exception e)
		{
			Core.getLogger(Agent.LogNode).error("Error stopping sub: "+ e.getMessage());
		}
		
		agent.pullSub(SubscriptionId+"-"+sub.getProjectId());
		Core.getLogger(Agent.LogNode).debug("Listening to: "+agent.getGcpSubscribers().size() + " Subscriptions");

		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "unsubscribeFromGCPSub";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
